name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Chọn phiên bản Python bạn muốn sử dụng

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Thay đổi thành lệnh cài đặt dependencies của bạn

      - name: Run Python script
        run: python lsg.py  # Thay đổi thành lệnh chạy script của bạn
