name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        uses: ./.github/workflows/setup.yml

      - name: Cài đặt các phụ thuộc
        run: pip install -r requirements.txt

      - name: Chạy script Python
        run: python lsg.py
