name: Run Telegram Bots

on:
  push:
    branches:
      - main  # Thay 'main' bằng tên nhánh chính của bạn nếu cần

jobs:
  build_bot1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies for Bot 1
        run: |
          pip install python-telegram-bot requests

      - name: Run Telegram Bot 1
        run: |
          python main.py  # Thay 'main.py' bằng tên file của bot 1 của bạn
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          # Thêm các biến môi trường khác nếu cần thiết

  build_bot2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies for Bot 2
        run: |
          pip install python-telegram-bot requests pytz

      - name: Install pytz
        run: |
          pip install pytz

      - name: Run Telegram Bot 2
        run: |
          python quayxu.py  # Thay 'quayxu.py' bằng tên file của bot 2 của bạn
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.QUAY_XU_BOT }}
          # Thêm các biến môi trường khác nếu cần thiết
