name: Run Telegram Bot

on:
  push:
    branches:
      - main  # Thay 'main' bằng tên nhánh chính của bạn nếu cần

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          pip install python-telegram-bot requests

      - name: Run Telegram Bot
        run: |
          python main.py  # Thay 'main.py' bằng tên file của bạn
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          # Thêm các biến môi trường khác nếu cần thiết
#r
