name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout mã nguồn
        uses: actions/checkout@v2

      - name: Cài đặt Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Chỉ định phiên bản Python bạn đang sử dụng

      - name: Cài đặt các phụ thuộc
        run: pip install -r requirements.txt

      - name: Chạy script Python
        run: python muahanghoantien1/lsg.py
